# KiPlot config file
kiplot:
  version: 1

global:
  resources_dir: '.resources'
  units: 'millimeters'

preflight:
  check_zone_fills: true
  ignore_unconnected: true
  run_drc: false
  update_xml: false

outputs:
  - name: 'gerbers'
    comment: "Gerbers for the board house"
    type: 'gerber'
    dir: 'gerberdir'
    options:
      # generic layer options
      exclude_edge_layer: false
      exclude_pads_from_silkscreen: false
      use_aux_axis_as_origin: false
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: true
      force_plot_invisible_refs_vals: false
      tent_vias: true

      # gerber options
      line_width: 0.15
      subtract_mask_from_silk: false
      use_protel_extensions: false
      gerber_precision: 4.6
      create_gerber_job_file: false
      use_gerber_x2_attributes: false
      use_gerber_net_attributes: false

    layers:
      - layer: 'F.Cu'
        suffix: 'F_Cu'
      - layer: 'F.Paste'
        suffix: 'F_Paste'
      - layer: 'F.SilkS'
        suffix: 'F_Silks'
      - layer: 'F.Mask'
        suffix: 'F_Mask'
      - layer: 'B.Cu'
        suffix: 'B_Cu'
      - layer: 'B.Paste'
        suffix: 'B_Paste'
      - layer: 'B.SilkS'
        suffix: 'B_Silks'
      - layer: 'B.Mask'
        suffix: 'B_Mask'
      - layer: 'B.Mask'
        suffix: 'B_Mask'

  - name: 'excellon_drill'
    comment: "Excellon drill files"
    type: 'excellon'
    dir: 'gerberdir'
    options:
      metric_units: true
      pth_and_npth_single_file: false
      use_aux_axis_as_origin: false
      minimal_header: false
      mirror_y_axis: false
      map:
        type: 'gerber'

